### ISSUE TITLE
Thank you for this repo!

### ISSUE THREAD

**Issue by ekm507** [zer0-x/krunner-currency#1]
I just want to say my regards and thanks for making this nice repository. ♥

I was trying to make my own krunner plugin with python but had no idea where to start. then I saw your repository and hopefully I can use yours to learn about things and make my own plugin.

BTW, is there any tutorials for making a krunner plugin out there? I didn't find any!

thank you.

**Comment by zefr0x** [comment]
It’s my pleasure!

Creating krunner plugins is very easy unexpectedly as long as you have programming knowledge. However, there are few plugins for krunner compared to other runners, perhaps due to the lack of resources.

First, you should know that plugins written in _C++_ are more compatible and have access to more functionalities, but in other languages you can communicate with krunner via the inter-process communication protocol _D-Bus_ which you have an access to from any programming language. Most of the functionalities can be obtained but not like in _C++_. You will give krunner a `.desktop` file for it to know some information about the plugin and how to communicate with it and a `.service` file to auto start the plugin, which will run as a separate process.

You should take a lock on the [_D-Bus_ documentation](https://dbus.freedesktop.org/doc/dbus-specification.html#introduction) or its [wikipedia page](https://en.wikipedia.org/wiki/D-Bus) and [python-dbus](https://dbus.freedesktop.org/doc/dbus-python/tutorial.html) to have a simple idea about it, so you can understand what you are doing. You should also install ` Qt QDBusViewer`, which is a GUI for D-Bus where you can debug your app and take a look on another app methods that you can use or any thing. It will be useful also if you want your plugin to communicate with `klipper` to add some text to the clip board or send a notification to the user or any other useful thing in your system. Some linux desktop apps has a D-Bus interface that you can use, take your time exploring them.

There are two sources to know what you should do in your plugin, the first is a xml file in the krunner framework source code [repository in KDE's gitlab](https://invent.kde.org/frameworks/krunner/-/blob/master/src/data/org.kde.krunner1.xml), where you can find the methods that you can define in you D-Bus interface, there input and there output. The second source is two KDevelop templates made by  _Alexander Lohnau_ in github: [simple_krunner_python_template](https://github.com/alex1701c/KDevelopTemplates/tree/master/krunner_dbus_templates/simple_krunner_python_template), [modular_krunner_python_template](https://github.com/alex1701c/KDevelopTemplates/tree/master/krunner_dbus_templates/modular_krunner_python_template).

Finally, to use some nateve looking icons in your plugin you can install `Cuttlefish (plasma-sdk)` to browse the available icons in your icons themes in KDE, for example breeze icons.
